version: '3'

services:
  lp_app1:
    container_name: lp_app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:4001:3000'

  lp_app2:
    container_name: lp_app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:4002:3000'

  lp_app3:
    container_name: lp_app3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:4003:3000'
