name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

env:
  WORKING_DIRECTORY: 'boletaai_lp'
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # UP APPLICATION
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_PUB_KEY_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            cd boletaai_lp
            docker compose stop
            git checkout develop
            git pull origin develop
            docker compose build --no-cache
            docker compose up -d
