name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  WORKING_DIRECTORY: 'boletaai_lp'
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # UP APPLICATION
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRD }}
          username: ${{ secrets.SSH_USER_PRD }}
          key: ${{ secrets.SSH_KEY_PRD }}
          port: ${{ secrets.SSH_PORT_PRD }}
          script: |
            cd boletaai_lp
            docker compose stop
            git checkout main
            git pull origin main
            docker compose build --no-cache
            docker compose up -d
