name: CI_DEVELOP

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

env:
  WORKING_DIRECTORY: 'boletaai_lp'
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # UP APPLICATION
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          password: ${{ secrets.SSH_PASSWORD_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            cd boletaai_lp
            docker compose stop
            git checkout develop
            git config pull.rebase false
            git pull origin develop
            echo "REACT_APP_API_URL=https://dev.app.boleta.ai/api" > .env
            echo "REACT_APP_APP_URL=https://dev.app.boleta.ai" >> .env
            docker compose build --no-cache
            docker compose up -d
